version: '3.7'
services:
  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    group_add:
      - "0"
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      - //usr/local/bin/docker:/usr/local/bin/docker
